<a href="https://colab.research.google.com/github/yuganshnirwan/Data-Wrangling/blob/main/practical_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 12
## Data Wrangling
### to perform preprocessing on a dataset and dealing with missing values
#### Name Aarya Yugansh Nirwan
##### A1  PRN:25070123004

In [ ]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'A1':[11,21,np.nan],'A2':[15,np.nan,np.nan],'A3':[10,20,30]})
df1

     A1    A2  A3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.isna () #boolean Function

      A1     A2     A3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.isna().sum() #ColumnWise na values

A1    1
A2    2
A3    0
dtype: int64

In [ ]:
df1.dropna() #NaN rows are dropped

     A1    A2  A3
0  11.0  15.0  10

In [ ]:
df1.fillna(value='Yugansh') #Acts as DEFAULT value

        A1       A2  A3
0     11.0     15.0  10
1     21.0  Yugansh  20
2  Yugansh  Yugansh  30

In [ ]:
df1.fillna(df1.mean()) #mean values of columns are calculated

     A1    A2  A3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [ ]:
import pandas as pd
data = {

"Roll No": [101, 102, 103, 104, 105],

"Name": ["Asha", "Yugansh", "Meera", "Karan", "Anil"],

"Age": [20, "-", 21, 20, "22"],

"Marks": [85, 90, "-", 88, 76],

"Department": ["CSE", "IT", "CSE", "CSE", "E&TC"],

"Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10-06-2023"]
}
df=pd.DataFrame(data)
df

   Roll No     Name Age Marks Department Admission_Date
0      101     Asha  20    85        CSE     01-06-2023
1      102  Yugansh   -    90         IT     03-06-2023
2      103    Meera  21     -        CSE     05-06-2023
3      104    Karan  20    88        CSE     07-06-2023
4      105     Anil  22    76       E&TC     10-06-2023

In [ ]:
#Step 2: Replace '-' with NaN to mark missing values df.replace("-", np.nan, inplace=True) I

df.replace("-",np.nan,inplace=True)

#Convert columns to numeric where needed

df["Age"] = pd.to_numeric(df["Age"], errors='coerce')
df["Marks"] = pd.to_numeric(df["Marks"], errors='coerce')

In [ ]:
#Step 3 checking missing values
print("\Missing Values:")
print(df.isnull().sum())

\Missing Values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

<>:2: SyntaxWarning: invalid escape sequence '\M'
<>:2: SyntaxWarning: invalid escape sequence '\M'
/tmp/ipykernel_274/41788304.py:2: SyntaxWarning: invalid escape sequence '\M'
  print("\Missing Values:")

In [ ]:
#Fill missing Age with mean
df["Age"].fillna(df["Age"].mean(),inplace=True)
df

/tmp/ipykernel_274/2787495670.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

   Roll No     Name    Age  Marks Department Admission_Date
0      101     Asha  20.00   85.0        CSE     01-06-2023
1      102  Yugansh  20.75   90.0         IT     03-06-2023
2      103    Meera  21.00    NaN        CSE     05-06-2023
3      104    Karan  20.00   88.0        CSE     07-06-2023
4      105     Anil  22.00   76.0       E&TC     10-06-2023

In [ ]:
#Step 5 :Fix inconsistent text formatting
df["Department"] = df["Department"].str.lower()
df

   Roll No     Name    Age  Marks Department Admission_Date
0      101     Asha  20.00   85.0        cse     01-06-2023
1      102  Yugansh  20.75   90.0         it     03-06-2023
2      103    Meera  21.00    NaN        cse     05-06-2023
3      104    Karan  20.00   88.0        cse     07-06-2023
4      105     Anil  22.00   76.0       e&tc     10-06-2023

In [ ]:
#Step 6: Convert admission_date to standard datetime format
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], errors='coerce')
df

   Roll No     Name    Age  Marks Department Admission_Date
0      101     Asha  20.00   85.0        cse     2023-01-06
1      102  Yugansh  20.75   90.0         it     2023-03-06
2      103    Meera  21.00    NaN        cse     2023-05-06
3      104    Karan  20.00   88.0        cse     2023-07-06
4      105     Anil  22.00   76.0       e&tc     2023-10-06

In [ ]:
#Step 8 : save cleaned Dataset

In [ ]:
df.to_csv("cleaned_student_data.csv",index=False)
print("\nCleaned CSV file saved as cleaned_Student_data.csv")

Cleaned CSV file saved as cleaned_Student_data.csv

In [ ]:
#Upload the dataset
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df=pd.read_csv('/content/Cars93.csv')
print(df.isna().sum())
df['Luggage.room']=df['Luggage.room'].fillna(df['Luggage.room'].mean())

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
df['AirBags']=df['AirBags'].fillna(df['AirBags'].mode().values[0])
print(df.isna().sum())
df

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    2
Luggage.room      0
dtype: int64

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000